language: generic
sudo: required
services:
  - docker

before_install:
  - ls
  - docker build -t bnpavlov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bnpavlov/react-test npm test

after_success:
  - docker build -t bnpavlov/multi-client ./client
  - docker build -t bnpavlov/multi-nginx ./nginx
  - docker build -t bnpavlov/multi-server ./server
  - docker build -t bnpavlov/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push bnpavlov/multi-client
  - docker push bnpavlov/multi-nginx
  - docker push bnpavlov/multi-server
  - docker push bnpavlov/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: 'eu-west-1'
    app: 'multi-docker'
    env: 'MultiDocker-env'
    bucket_name: 'elasticbeanstalk-eu-west-1-923445559289'
    bucket_path: 'docker-multi'
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY